spring.application.name=cbbackend

# jwt config (clave de al menos 32 caracteres para HS256)
jwt.secret=NC/YBq7n9p9wpVCM0XITQAx4NDE0521Vr5c7AW5/+QR1zJFF28EgVQdox7RsLk+97ZA3cC9ssn752cb61dL3ug==

# h2 config
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Que Hibernate genere el esquema automáticamente
spring.jpa.hibernate.ddl-auto=update

# Habilitar la consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.defer-datasource-initialization=true

# PostgreSQL
# spring.datasource.url=jdbc:postgresql://localhost:5432/banco_credito
# spring.datasource.username=postgres
# spring.datasource.password=12345

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# spring.jpa.hibernate.ddl-auto=update
# spring.sql.init.mode=always

# spring.jpa.defer-datasource-initialization=true