spring.application.name=cbbackend

# h2 config
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Que Hibernate genere el esquema automáticamente
spring.jpa.hibernate.ddl-auto=update

# Habilitar la consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.defer-datasource-initialization=true

# PostgreSQL
# spring.datasource.url=jdbc:postgresql://localhost:5432/banco_credito
# spring.datasource.username=postgres
# spring.datasource.password=12345

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# spring.jpa.hibernate.ddl-auto=update
# spring.sql.init.mode=always

# spring.jpa.defer-datasource-initialization=true